version: '3'
services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper-1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        volumes: 
            - /Users/murillo.pezzuol/development/docker/volumes/zookeeper:/var/lib/confluent-control-center

    kafka-1:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-1
        depends_on:
            - zookeeper-1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
        volumes: 
            - /Users/murillo.pezzuol/development/docker/volumes/kafka:/var/lib/confluent-control-center
